<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\StartButtonBank
 *
 * @OA\Schema (
 *      schema="StartButtonBank",
 *      required={"startbutton_id","name","code"},
 *      @OA\Property(
 *          property="name",
 *          description="",
 *          readOnly=false,
 *          nullable=false,
 *          type="string",
 *      ),
 *      @OA\Property(
 *          property="code",
 *          description="",
 *          readOnly=false,
 *          nullable=false,
 *          type="string",
 *      ),
 *      @OA\Property(
 *          property="currency",
 *          description="",
 *          readOnly=false,
 *          nullable=true,
 *          type="string",
 *      ),
 *      @OA\Property(
 *          property="created_at",
 *          description="",
 *          readOnly=true,
 *          nullable=true,
 *          type="string",
 *          format="date-time"
 *      ),
 *      @OA\Property(
 *          property="updated_at",
 *          description="",
 *          readOnly=true,
 *          nullable=true,
 *          type="string",
 *          format="date-time"
 *      )
 * )
 * @property int $id
 * @property int $startbutton_id
 * @property string $name
 * @property string $code
 * @property string|null $currency
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank query()
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereCurrency($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereStartbuttonId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|StartButtonBank whereUpdatedAt($value)
 * @mixin \Eloquent
 */class StartButtonBank extends Model
{
    public $table = 'startbutton_banks';

    public $fillable = [
        'startbutton_id',
        'name',
        'code',
        'currency'
    ];

    protected $casts = [
        'name' => 'string',
        'code' => 'string',
        'currency' => 'string'
    ];

    public static array $rules = [
        'startbutton_id' => 'required',
        'name' => 'required|string|max:255',
        'code' => 'required|string|max:255',
        'currency' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $nuage_env = env("NUAGE_ENV");

        if(strtoupper($nuage_env) === strtoupper("SANDBOX")) {
            $this->connection = env("AUTH_DB_CONNECTION", "mysql");
        }

    }

    public function toApiArray(): array
    {
        return [
            "name"=>$this->name,
            "code"=>$this->code,
            "currency"=>$this->currency
        ]; // TODO: Change the autogenerated stub
    }


}
